### ISSUE TITLE
Why does your modification in time_compare.v make the design meet timing?

### ISSUE THREAD

**Issue by frestuc** [ucsdsysnet/SweepSense#1]
Hi guys,

Nice work and overall design--
May I ask why you had to modify time_compare.v in that way to meet timing? What is the rationale there?

Thanks a lot,
Francesco

**Comment by mkhazraee** [comment]
Hi Francesco,

ISE was using a 64bit comparator for "late" signal in time_compare.v, which is a rather long logical path due to carry of the subtraction. I made it more parallel by splitting it in two 32bit comparators and a 2 bit logic to cut the critical path. Since design was becoming larger ISE had a harder time to meet timing and this helped.

Moein

**Comment by frestuc** [comment]
Hi Moein, it makes perfect sense. Thanks.
